### ISSUE TITLE
URL parameter not properly escaped

### ISSUE THREAD

**Issue by weppos** [authy/authy-ruby#10]
We're using the client in a Rails project and from time to time the following error is raised.

> URI::InvalidURIErrorbad URI(is not URI?): https://api.authy.com//protected/json/verify/foo bar/000000

The origin of the issue is that the library takes the `token` parameter and [uses it immediately without any further sanitization](https://github.com/authy/authy-ruby/blob/master/lib/authy/api.rb#L38).

You can reproduce the issue with the following example

```ruby
Authy::API.verify(:id => user.authy_id, :token => 'token with space', :force => true)
```

We can indeed validate the user input, but I assume the library should not trust a parameter, especially if this parameter is used to generate an URL path like in this case.

You may want to sanitize or validate every input that is part of an URL.

**Comment by dcu** [comment]
Closing. this was already fixed.
