### ISSUE TITLE
Authy cannot verify token

### ISSUE THREAD

**Issue by vf-sohail** [authy/authy-ruby#17]
I am using authy and getting issue in verifying user. I successfully registered the user but failed to verify.

When i check user status it returns

{"status"=>{"authy_id"=>xxxxxx, "confirmed"=>true, "registered"=>false, "country_code"=>92, "phone_number"=>"XXX-XXX-3156", "devices"=>[], "has_hard_token"=>false, "account_disabled"=>false}, "message"=>"User status.", "success"=>true}

When i was verifying user by

Authy::API.verify(:id => xxxxxx, :token => token_on_app, :force => true)

it gives

{"success"=>false, "message"=>"Token format is invalid", "errors"=>{"message"=>"Token format is invalid"}}

but i am giving the correct token.

Please tell me what goes wrong? Thanks

**Comment by dcu** [comment]
`token_on_app` should be between 6 and 12 digits, otherwise the validation fails.
