### ISSUE TITLE
Any specific API for updating the phone number of already registered user?

### ISSUE THREAD

**Issue by shivabhusal** [authy/authy-ruby#30]

**Comment by plicjo** [comment]
I checked their API and there is no update method.

In my app, I have it delete the user and re-create a new one with new attributes in the event that I need to update something.

It's kinda lame, but it works.

**Comment by LucasVidal** [comment]
@plicjo you can't change the phone on your user's behalf. Only an authenticated user can do that through the Authy apps or here: https://www.authy.com/phones/change. The purpose of that is to prevent account takeovers.
