### ISSUE TITLE
Are there plans to maintain this gem?

### ISSUE THREAD

**Issue by plicjo** [authy/authy-ruby#31]
I'm getting a few errors from inside of the `Response` class in this gem?

As this gem is related to my app's security, I'm hesistant to fork it and maintain it myself.

I'd love to submit PR's to this repo, but I see 3 open pull requests that have remained stagnant for over a year.

Are there plans to maintain this repo? Would you like a maintainer?

**Comment by LucasVidal** [comment]
We'll be happy to review your PR from your fork

**Comment by plicjo** [comment]
Ok, great. Incoming!
