### ISSUE TITLE
How do I run tests with rspec without Twilio charging my account?

### ISSUE THREAD

**Issue by daydream05** [authy/authy-ruby#36]
I'm using the phone verification api and I'd like to test my phone verification controller for successful cases but I'm not sure I would be charged for this.

**Comment by LucasVidal** [comment]
Hello, @daydream05 , and sorry for taking so long to reply. We used to have a sandbox environment, but it was deprecated. 

Sadly we don't have a way to open an account that sends SMSs without charging for those. The kind of tests you want to run should lead you to mock the service instead.

Cheers
